### ISSUE TITLE
Error Failed to instanciate

### ISSUE THREAD

**Issue by Chry1911** [ChannelApe/shopify-sdk#116]
When i'm trying to execute this

final ShopifySdk shopifySdk = ShopifySdk.newBuilder()
  .withSubdomain(subdomain)
  .withAccessToken(accessToken).build();
final ShopifyShop shopifyShop = shopifySdk.getShop();

Gives an error failed to instanciate.
My subdomain i think must be something like = "mydomain.shopify.com"
My accessToken i think must be my api access token.

Here the error:

`There was an exception while trying to navigate to 'customers' with the root cause 'java.lang.ClassNotFoundException: javax.ws.rs.ext.MessageBodyReader'
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.ch.goodcode.attecloud.views.customers.CustomersView': Failed to instantiate [com.ch.goodcode.attecloud.views.customers.CustomersView]: Constructor threw exception
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:326)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:314)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:320)
	at com.vaadin.flow.spring.SpringInstantiator.getOrCreate(SpringInstantiator.java:121)
	at com.vaadin.flow.di.Instantiator.createRouteTarget(Instantiator.java:136)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$getRouteTarget$1(AbstractNavigationStateRenderer.java:133)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.getRouteTarget(AbstractNavigationStateRenderer.java:132)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEventAndPopulateChain(AbstractNavigationStateRenderer.java:493)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.createChainIfEmptyAndExecuteBeforeEnterNavigation(AbstractNavigationStateRenderer.java:474)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:212)
	at com.vaadin.flow.component.internal.JavaScriptNavigationStateRenderer.handle(JavaScriptNavigationStateRenderer.java:78)
	at com.vaadin.flow.component.UI.handleNavigation(UI.java:1785)
	at com.vaadin.flow.component.UI.renderViewForRoute(UI.java:1748)
	at com.vaadin.flow.component.UI.lambda$connectClient$cfbe2c41$1(UI.java:1657)
	at com.vaadin.flow.component.UI.connectClient(UI.java:1665)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`

**Comment by whoamizq** [comment]
Obviously, there is no exception in this class, please ask if it is jdk8
