### ISSUE TITLE
Updates for CustomCollection and SmartCollection

### ISSUE THREAD

**Issue by kennethjor** [ChannelApe/shopify-sdk#41]
I'd like to be able to update (and create?) custom collections and smart collections via the REST API.

**Comment by kennethjor** [comment]
I've been looking at the implementation for this for products, which is based on the builder pattern. Is this code auto-generated in any way? I'd like to keep the same style, but I'd also rather not have to hand-write all of this stuff, if I can avoid it.

**Comment by surichao** [comment]
public static void main(String[] args) {
		final ShopifySdk shopifySdk = ShopifySdk.newBuilder()
				.withSubdomain("**-***.myshopify.com")
				.withAccessToken("******").build();
		final ShopifyShop shopifyShop = shopifySdk.getShop();
		System.out.println(shopifyShop.getShop());
	}

I tried to use this SKD but this exception was thrown from the beginning

	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
	at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
	at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:419)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:319)
	at com.shopify.ShopifySdk.lambda$get$4(ShopifySdk.java:917)
	at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
	at com.github.rholder.retry.Retryer.call(Retryer.java:160)
	at com.shopify.ShopifySdk.invokeResponseCallable(ShopifySdk.java:969)
	at com.shopify.ShopifySdk.get(ShopifySdk.java:918)
	at com.shopify.ShopifySdk.getShop(ShopifySdk.java:501)
	at com.shopify.ShopifySdk.getWebTarget(ShopifySdk.java:1043)
	at com.shopify.ShopifySdk.getShop(ShopifySdk.java:501)

**Comment by kennethjor** [comment]
@surichao That's unrelated to this issue, you should probably open a new issue.

However, your `withSubdomain` call should _just_ be your subdomain. So if your admin page is "my-cool-shop.myshopify.com" then you should call `withSubdomain("my-cool-shop"). Also, when posting stack traces, please post the full stack trace, not just a part of it.

**Comment by surichao** [comment]
I have solved the problem, the subdomain I gave is correct, but I did not post it. The actual problem is that what I pull from the maven repository is not working properly, because the dependency package in the jar is actually not available. I packaged the source code on github and found that the dependency is not entered. I need to manually source the pom The above dependency was added to my project

**Comment by kennethjor** [comment]
> the dependency package in the jar is actually not available

@surichao Yeah, you're doing something wrong. If you continue to have problems, please open a new issue and leave this one on-topic.

**Comment by kennethjor** [comment]
@rjdavis3 I had a look at implementing this. The code for the update request classes looks a tad complicated. Do you use a specific plugin to help with generating the builder classes, or are these written by hand?
