### ISSUE TITLE
An exception occurred while making an API call to shopify: 12 on attempt number 33 and {} seconds since first attempt

### ISSUE THREAD

**Issue by charinduedirisuriya** [ChannelApe/shopify-sdk#60]
Facing the below error. Can somebody provide an example for the usage of the the SDK?

I've initialized it as below.

```
ShopifySdk shopifySdk = ShopifySdk.newBuilder()
                .withSubdomain("mystore.myshopify.com")
                .withAccessToken("mytoken_xxxxx").build();
        ShopifyShop shopifyShop = shopifySdk.getShop();
```

Is it correct?

Facing the below issue - `An exception occurred while making an API call to shopify: 12 on attempt number 33 and {} seconds since first attempt
`
```
java.lang.IllegalStateException: InjectionManagerFactory not found.
	at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:74) ~[jersey-common-2.32.jar:na]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_152]
	at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:74) ~[jersey-common-2.32.jar:na]
	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:44) ~[jersey-common-2.32.jar:na]
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:412) ~[jersey-client-2.32.jar:na]
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317) ~[jersey-common-2.32.jar:na]
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:814) ~[jersey-client-2.32.jar:na]
	at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:219) ~[jersey-client-2.32.jar:na]
	at org.glassfish.jersey.client.ClientRequest.getInjectionManager(ClientRequest.java:610) ~[jersey-client-2.32.jar:na]
	at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:364) ~[jersey-client-2.32.jar:na]
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:199) ~[jersey-client-2.32.jar:na]
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:36) ~[jersey-client-2.32.jar:na]
	at com.shopify.ShopifySdk.lambda$get$4(ShopifySdk.java:939) [shopify-sdk-2.3.0.jar:na]
	at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78) ~[guava-retrying-2.0.0.jar:na]
	at com.github.rholder.retry.Retryer.call(Retryer.java:160) ~[guava-retrying-2.0.0.jar:na]
	at com.shopify.ShopifySdk.invokeResponseCallable(ShopifySdk.java:992) [shopify-sdk-2.3.0.jar:na]
	at com.shopify.ShopifySdk.get(ShopifySdk.java:941) [shopify-sdk-2.3.0.jar:na]
	at com.shopify.ShopifySdk.getShop(ShopifySdk.java:523) [shopify-sdk-2.3.0.jar:na]
	at com.shopify.ShopifySdk.getWebTarget(ShopifySdk.java:1077) [shopify-sdk-2.3.0.jar:na]
	at com.shopify.ShopifySdk.getShop(ShopifySdk.java:523) [shopify-sdk-2.3.0.jar:na]
```

**Comment by charinduedirisuriya** [comment]
Solved the issue by adding the following maven dependency.

<dependency>
    <groupId>org.glassfish.jersey.inject</groupId>
    <artifactId>jersey-hk2</artifactId>
    <version>2.26</version>
</dependency>
